controller:
  ros__parameters:
    cmd_vel_topic : '/auto/cmd_vel'
    odom_topic : 'odom'
    set_active_topic : 'set_active'
    aruco_pose_topic : '/aruco_detector/marker'

    aruco_frame_id : 'fiducial_rotated'
    robot_base_frame_id : 'base_link'

    scan_around_vel : 0.25

    max_linear_vel : 1.0
    min_linear_vel : 0.0
    max_angular_vel : 1.57
    min_angular_vel : 0.0

    kp_linear : 1.0
    kp_angular : 1.0
    max_kp_linear : 3.0
    max_kp_angular : 5.0

    aruco_pose_timeout : 0.3
    aruco_pose_offset : 0.5
    goal_pose_tolerance : 1.0
    controller_frequency : 20.0

