# Format is namespace_name/node_name
front_camera/gscam_publisher:
  ros__parameters:
    # gscam_config: 'videotestsrc pattern=ball ! video/x-raw, format=BGRx ! videoconvert'
    # gscam_config: 'videotestsrc pattern=ball ! video/x-raw, format=BGRx ! videoconvert ! jpegenc'
    gscam_config: 'v4l2src device=/dev/video8 ! video/x-raw,width=1280,height=800,framerate=30/1,format=NV12 ! videoflip method=4 ! queue ! mppjpegenc header-mode=1 gop=1 qos=1'
    image_encoding: 'jpeg' # ("rgb8", "mono8", "yuv422", "jpeg")
    preroll: False # default
    use_gst_timestamps: False # default
    sync_sink: True # default
    frame_id: 'front_camera_optical'
